sudo: true # Enable container-based infrastructure

language: scala
scala:
        - 2.10.4

# cache: apt # Enable caching on APT when it is available for our repo

os:
    - linux
    - osx

branches:
    only:
        - master
        - dev-master

env:
        - CCNL_HOME="/home/travis/build/cn-uofbasel/ccn-lite" PATH=$PATH:"$CCNL_HOME/bin" USE_NFN=1

addons:
    apt:
        packages:
            - libssl-dev
            - build-essential
#            - linux-headers-$(uname -r)

before_install:
        - sudo add-apt-repository -y ppa:webupd8team/java
        - sudo apt-get update && sudo apt-get install oracle-java8-installer
        - java -version


install:
    - cd ..
    - git clone https://github.com/cn-uofbasel/ccn-lite.git
    - cd -

script:
    - cd $CCNL_HOME/src
    - pwd
    - echo $CCNL_HOME
    - echo ~  
    - make clean all
    - cd -
    - sbt compile
#    - sbt 'runMain runnables.evaluation.WordcountApp'
